apiVersion: extensions/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gateway
    spec:
      containers:
      - image: gateway
        name: gateway
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
