apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.14.0 (fa706f2)
  creationTimestamp: null
  labels:
    io.kompose.service: stateful
  name: stateful
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: stateful
    spec:
      containers:
      - image: stateful
        name: stateful
        resources: {}
        volumeMounts:
        - mountPath: /tmp
          name: stateful-claim0
      restartPolicy: Always
      volumes:
      - name: stateful-claim0
        persistentVolumeClaim:
          claimName: stateful-claim0
status: {}
